# Anotações e exercícios

In [9]:
# assim se calcula raiz quadrada

10**(1/2)

3.1622776601683795

# Funções para explorar dados

In [ ]:
df.info()
df.describe()
df.isna().sum()
df.value_counts()
df['artist'].unique() # retorna os valores únicos dessa coluna.
df['artist'].nunique() # retorna o número de valores únicos.
df.shape
df.size
df.columns
df.memory_usage()
df.nsmallest(3, 'dnce') # retorna os três menores valores da coluna dnce.
df.nlargest(3, 'dnce')
df.drop_duplicates(subset = ['title'], keep = 'last') # deleta registros duplicados e mantém o mais recente.
df.fillna(0)
df.T # transpõe a tabela
df.sample(n = 10) # pega dez registros aleatórios do dataframe.
len(df)


# Como encontrar valores específicos no dataframe

In [ ]:
df.query("artist == 'Ariana Grande'") # aqui tem que usar aspas duplas pois precisa de aspas simples no nome da artista. Se não fizer isso não funciona.
df.loc[df['artist'] == "Ariana Grande"]
df.filter(like = 'Ariana')
df.isin(['Ariana Grand', 'Maroon 5', 'DNCE'])
(df['artist'] == 'QUEEN').any()

# Operações com dataframe

In [ ]:
df.drop(columns = ['pop'])
df['acous'].mean()
df['acous'].min()
df['acous'].max()
df.agg({'acous': 'mean', 'dur': 'max'})
df['dur'].cumsum() # soma cumulativa.
df.sort_values(by = 'dur', ascending = False)
df['bpm'].astype(str)
pd.get_dummies(df, columns = ['artist'])
df.assign(dnce_nrgy = lambda df: df['dnce'] * df['nrgy']) # cria nova coluna que é o produto da multiplicação de outras duas colunas.
df.groupby('artist').count()
df.groupby('artist')['title'].count()
df.groupby('artist')['title', 'year'].count()
df.groupby(['artist', 'year']).agg({'year': 'count', 'dur': 'mean'})
df_grouped = df.groupby('year')
df_grouped.ngroups
df_grouped.groups
df_grouped_size()
df_grouped.get_group(2015)

# Merging datasets

In [ ]:
df.merge(df2, left_on = 'artist', right_on = 'Artists', how = 'left') # relembrar left, right, inner do SQL nessa parte.
df.merge(df2, left_on = 'artist', right_on = 'Artist', how = 'left', indicator = True) # indica de qual dataset veio cada coluna.
df.join(df2)
df.append(df2) # aqui se junta os datasets pelas linhas, se não tiver determinada coluna no dataset que foi "apendado", aparece um NaN na coluna.
df.corr()
df.groupby('artist')['title', 'year'].count().reset_index() # mostrar mais sobre concatenação de funções no pandas.
df[:13].style.background_gradient(axis = 0, cmap = 'YlOrRd')



In [1]:
import numpy as np

In [2]:
vetor_linha = np.array([1,2,3])
print(vetor_linha)

[1 2 3]


In [5]:
vetor_column = np.array([[1],[2],[3]])
print(vetor_column)

[[1]
 [2]
 [3]]


In [4]:
matriz = np.array([[14,62,3], [44,5,61], [7,86,9]])
print(matriz)

[[14 62  3]
 [44  5 61]
 [ 7 86  9]]


In [6]:
np.linspace(0, 20, num = 5)

array([ 0.,  5., 10., 15., 20.])

In [7]:
print(np.random.randint(0, 11, 3))

[3 9 0]


# Informações sobre os dados

In [8]:
print(matriz.shape)

(3, 3)


In [9]:
print(matriz.dtype)

int64


In [10]:
print(matriz.size)

9


In [12]:
print(matriz.ndim)

2


In [13]:
print(np.min(matriz))

3


In [14]:
print(np.max(matriz))

86


In [15]:
print(np.max(matriz, axis = 0)) # elemento máximo em cada coluna.

[44 86 61]


In [16]:
print(np.max(matriz, axis = 1)) # elemento máximo em cada linha.

[62 61 86]


In [17]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [19]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
s = np.array([1, 9, 15, 4])
np.sort(s)

array([ 1,  4,  9, 15])

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# desvio padrão.
print(np.std(matriz))

29.5296461204668


In [27]:
# percentil.
np.percentile(a, 10)

1.3

In [28]:
# variância.
print(np.var(matriz))

871.9999999999999


In [29]:
print(matriz.T)

[[14 44  7]
 [62  5 86]
 [ 3 61  9]]


In [30]:
# Soma de matrizes.
matrix1 = np.array([[14, 2, 3], [48, 5, 6]])
matrix2 = np.array([[1, 21, 3], [4, 54, 66]])
print(np.add(matrix1, matrix2))

[[15 23  6]
 [52 59 72]]


In [31]:
print(np.subtract(matrix1, matrix2))

[[ 13 -19   0]
 [ 44 -49 -60]]


In [32]:
print(matrix1 * matrix2)

[[ 14  42   9]
 [192 270 396]]


In [34]:
print(np.mean(matriz))

32.333333333333336


In [37]:
# Cálculo de diagonais.
# Diagonal principal:
print(matriz.diagonal())

[14  5  9]


In [38]:
# diagonal acima da diagonal principal.
print(matriz.diagonal(offset = 1))

[62 61]


In [39]:
# diagonal abaixo da diagonal principal.
print(matriz.diagonal(offset = -1))

[44 86]


In [40]:
matriz

array([[14, 62,  3],
       [44,  5, 61],
       [ 7, 86,  9]])

In [41]:
# matriz inversa
print(np.linalg.inv(matriz))

[[ 0.08719926  0.00502976 -0.06315701]
 [-0.00051974 -0.00176042  0.01210495]
 [-0.06285523  0.01290972  0.04456367]]


In [42]:
# adicionando elementos ao array.
# criando a função para adicionar os elementos:
add_100 = lambda i: i + 100

In [45]:
# converter em uma função vetorizada.
vectorized_add_100 = np.vectorize(add_100)

In [44]:
# aplicando as funções.
print(vectorized_add_100(matriz))

[[114 162 103]
 [144 105 161]
 [107 186 109]]


In [46]:
five_up = (a >= 5)
print(a[five_up])

[]


In [47]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[2 4]


In [48]:
c = a[(a > 2) & (a < 11)]
print(c)

[3 4]


In [49]:
five_up = (a > 5) | (a == 5)
print(five_up)

[False False False False]


In [50]:
b = np.nonzero(a < 5)
print(b)

(array([0, 1, 2, 3]),)


In [51]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [52]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [53]:
unique_values = np.unique(a)
print(unique_values)

[1 2 3 4]
